name: Test

on:
    push:
        branches:
          - "master"
    pull_request:
        branches:
            - "master"

jobs:
    test:
        name: Node ${{ matrix.node }} on ${{ matrix.os }}
        runs-on: ${{ matrix.os }}

        strategy:
          fail-fast: true
          matrix:
            node: [8,10,12,14,16]
            os: [ubuntu-latest]
        steps:
          - name: Clone repository
            uses: actions/checkout@v2

          - name: Set Node.js version
            uses: actions/setup-node@v1
            with:
                node-version: ${{ matrix.node }}

          - name: Install npm dependencies
            run: npm install

          - name: Run tests
            run: npm run coverage

          - name: Coveralls
            uses: coverallsapp/github-action@master
            with:
                github-token: ${{ secrets.GITHUB_TOKEN }}
                flag-name: ${{matrix.os}}-node-${{ matrix.node }}
                parallel: true

    finish:
        needs: test
        runs-on: ubuntu-latest
        steps:
        - name: Coveralls Finished
          uses: coverallsapp/github-action@master
          with:
            github-token: ${{ secrets.GITHUB_TOKEN }}
            parallel-finished: true
