name: Test

on:
    push:
        branches:
          - "master"
    pull_request:
        branches:
            - "master"

jobs:
    build:
        runs-on: ubuntu-latest

        strategy:
          fail-fast: true
          matrix:
            node_version:
                - 8.x
                - 10.x
                - 12.x
                - 14.x
                - 16.x
        steps:
          - name: CHECK-OUT GIT REPOSITORY
            uses: actions/checkout@v2
          - name: INSTALL PROJECT DEPENDENCIES
            run: npm install
          - name: Test
            uses: actions/setup-node@v1
            with:
                node-version: ${{ matrix.node-version }}
          - run: npm run coverage
          - run: npm run coveralls
